print("Hi today we will be making a madlib. I will ask you questions and you will answer.")
name = input("Whats you name you like.")
print(f"Hi {name} nice to meet you")
animal = input("please pick a animal.")
item = input("please pick a item.")
food = input("pick a food please.")
place = input("pick a place please.")
activity = input ("please pick and activity and make it funny.")
print(f"{name} the {animal} got up and went to...")
print(f"{place} was a nice and beautiful.")
print(f"{name} loved {place}.")
print(f"It was the only place they felt confertable.")
print (f"{name} loved to eat {food} there")
print(f"{name} loved to think about {activity}")
print(f"there was a {item} that was in {place} and {name} the {animal} would look at it for hours.")
print ("thank you for participating have a great day. Good bye")